apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
          listen 80 default_server;
          listen [::]:80 default_server ipv6only=on;

          listen 443 ssl;

          root /usr/share/nginx/html;
          index index.html;

          server_name localhost;
          ssl_certificate /etc/nginx/ssl/tls.crt;
          ssl_certificate_key /etc/nginx/ssl/tls.key;

          location / {
                  add_header my-forward $http_x_forwarded_for;
                  add_header my-client-ip $remote_addr;
                  add_header my-host $hostname;
                  try_files $uri $uri/ =404;
          }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    welcome to nginx