apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    svc: nginx
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: "my-port"
  selector:
    app: nginx